<p><strong>Download</strong>: <a href="/pdf/globest-sites-globest-2014-12-16-cohen-inflation-will-bring-investors-yield.pdf">globest-sites-globest-2014-12-16-cohen-inflation-will-bring-investors-yield.pdf</a></p>
<p>NEW YORK CITY—After 15 years as EVP of Malkin Securities Corp., Ned Cohen hung out his own shingle last month with two separate but related companies: NHCohen Partners, LLC, an investment firm, and NHCohen Capital LLC, an affiliated broker-dealer. GlobeSt.com sat down with the newly minted entrepreneur to get the back story behind this move for this EXCLUSIVE story.</p>
<p><em><strong>GlobeSt.com</strong>: Why did you want to create your own firm at this time?</em><br />
<p><strong>Ned Cohen</strong>: I saw an opportunity to provide the investors with whom I’ve worked the continued benefits of direct ownership of income producing real estate, which they no longer had once the Malkins created the Empire State Realty Trust.</p>
<p><em><strong>GlobeSt.com</strong>: What will you offer investors?</em></p>
<p><strong>Cohen</strong>: I intend to provide private placements that will involve securities issued by well-vetted investment sponsors. The sponsors will have very strong ethics and as well as a history of performance.</p>
<p><em><strong>GlobeSt.com</strong>: Why did you create both NHCohen Partners and NHCohen Capital, instead of just one firm?</em></p>
<p><strong>Cohen</strong>: NHCohen Capital is the vehicle through which I can offer securities; it’s a broker/dealer. NHCohen Partners is the holding company and the marketing arm that will provide investor services. That way, a sponsor who finds he has a few hundred investors in his deal won’t be put off by having to communicate with all of those investors.</p>
<p><em><strong>GlobeSt.com</strong>: Will you work on all types of properties or are there specific sectors you’ll focus on?</em></p>
<p><strong>Cohen</strong>: I’m going to be focusing on office, retail, multifamily, select-service hotels, possibly industrial and mixed-use properties. That seems broad but I intend to find the best in class sponsors in each of those areas. I won’t just work with any sponsor that comes through the door. Even though the Malkin company was known for office, we did retail, multifamily and industrial, and in my experience I’ve touched on the other areas.</em></p>
<p><em><strong>GlobeSt.com</strong>: What does the future hold for your firm and for the industry?</em></p>
<p><strong>Cohen</strong>: Market conditions are prime for channeling capital into alternative investments, particularly real estate. I think inflation is going to be a friend to real estate because it will allow investors to continue to get yield. The volatility of the public market is something people are sensitive too. I’m offering an alternative to equities.</p>
<p><strong>Original Link (globest.com)</strong>: <a href="http://www.globest.com/sites/globest/2014/12/16/cohen-inflation-will-bring-investors-yield/" target="_blank">http://www.globest.com/sites/globest/2014/12/16/cohen-inflation-will-bring-investors-yield/</a></p>
