<p><strong>Download</strong>: <a href="/pdf/globest-sites-globest-2014-11-10-former-malkin-exec-forms-real-estate-investment-firm.pdf">globest-sites-globest-2014-11-10-former-malkin-exec-forms-real-estate-investment-firm.pdf</a></p>
<p>NEW YORK CITY—Ned H. Cohen, a former executive vice president with Malkin Securities Corp., has formed his own Park Avenue-based investment firm NHCohen Partners, LLC.</p>
<p>The 35-year real estate finance veteran also announced he formed NHCohen Capital LLC, an affiliated broker-dealer. The companies are based at 2 Park Ave.</p>
<p>NHCohen Partners will identify opportunities for investors to participate in limited partnerships that provide equity to well-established real estate entrepreneurs for investments in quality real estate. The firm also may seek attractive opportunities in other types of alternative investments. NHCohen Capital will be the placement agent for the securities issued by investment sponsors, company officials say.</p>
<p>Cohen most recently served for 15 years as executive vice president of Malkin Securities Corp. where he directed the securities offerings of the real estate syndications of Malkin Holdings LLC. Most of the Malkin portfolio—including the Empire State Building, which was syndicated in 1961—is now part of the publicly traded Empire State Realty Trust.</p>
<p>“More so than ever, there is a pressing need for private-equity vehicles though which high-net-worth individuals and family entities can take part in direct real estate ownership as a means of portfolio diversification,” says Cohen. “The invaluable perspective and insight I’ve been fortunate to acquire over the decades enables me to help clients meet their individual investment goals, and to work effectively with their registered advisors.”</p>
<p>NHCohen Partners will work only with well-established deal sponsors with successful track records, raising equity capital for conservatively leveraged income-producing real estate assets initially in the $15-million-to-$50-million range.</p>
<p>Cohen was a former partner of Bergman Real Estate Group in New Jersey, where he headed the firm’s acquisition and finance activities as well as its client advisory services. Previously, he was a vice president of Unicorp American Corp., where he led the analysis and acquisition of Lincoln Savings Bank’s $1.8-billion real estate portfolio.</p>
<p>He also served as vice president of real estate banking firm Eastdil Realty (now Eastdil Secured), where his clients included Chrysler Corp., Penn Mutual Life Insurance Co., New York State’s Urban Development Corp., and the Lake Placid Resort Hotel bankruptcy (which was the 1980 Winter Olympics headquarters). As a vice president of real estate syndicator Integrated Resources, Cohen oversaw the acquisition and underwriting of office buildings and shopping centers for limited partnership and public fund investors.</p>
<p>His career began in construction lending with what is now JPMorgan Chase Bank, following his graduation from Syracuse University. He recently was elected to serve on the Board of Advisors of 5 Stone Green Capital LLC, a real estate investment fund focused on sustainability and the use of clean energy.</p>
<p><strong>Original Link (globest.com)</strong>: <a href="http://www.globest.com/sites/globest/2014/11/10/former-malkin-exec-forms-real-estate-investment-firm/" target="_blank">Former Malkin Exec. Forms Real Estate Investment Firm</a></p>
