<p><strong>Download</strong>: <a href="/pdf/rew-online-2014-12-03-ned-cohen-starts-his-own-firm.pdf">hrew-online-2014-12-03-ned-cohen-starts-his-own-firm.pdf</a></p>
<p>Ned H. Cohen, a 35-year veteran of real estate finance, has formed a new Manhattan-based investment firm, NHCohen Partners LLC, along with an affiliated registered broker-dealer, NHCohen Capital LLC.</p>
<p>NHCohen Partners will identify opportunities for investors to participate in limited partnerships that provide equity to well-established real estate entrepreneurs for investments in quality real estate.</p>
<p>The firm also may seek attractive opportunities in other types of alternative investments. NHCohen Capital will be the placement agent for the securities issued by investment sponsors.</p>
<p>Cohen most recently served as executive vice president of Malkin Securities Corp. where he directed the securities offerings of the real estate syndications of Malkin Holdings LLC. Most of the Malkin portfolio – including the Empire State Building, which was syndicated in 1961 – is now part of the publicly traded Empire State Realty Trust.</p>
<p>“More so than ever, there is a pressing need for private-equity vehicles through which high-net-worth individuals and family entities can take part in direct real estate ownership as a means of portfolio diversification,” said Cohen. “The invaluable perspective and insight I’ve been fortunate to acquire over the decades enables me to help clients meet their investment goals, and to work effectively with their registered advisors.”</p>
<p>Cohen is a registered principal and operations professional with the Financial Industry Regulatory Authority (FINRA), and holds Series 22, 39, 63 and 99 securities licenses.</p>
<p>NHCohen Partners will raise equity capital for conservatively leveraged income-producing real estate assets initially in the $15-to-$50-million range.</p>
<p><strong>Original Link (rew-online.com)</strong>: <a href="http://rew-online.com/2014/12/03/ned-cohen-starts-his-own-firm/">Ned Cohen Starts His Own Firm</a></p>
