<p><strong>Download</strong>: <a href="/pdf/globest-sites-globest-2015-03-12-nhcohen-and-herrick-feinstein-team-up.pdf">globest-sites-globest-2015-03-12-nhcohen-and-herrick-feinstein-team-up.pdf</a></p>
<p>NEW YORK CITY—Real estate investment firm NHCohen Partners LLC and Herrick, Feinstein LLP, a leader in commercial real estate law since 1928, have formed a strategic alliance to provide long-term equity financing for the real estate industry.</p>
<p>Ned Cohen, founder and president of his eponymous firm, and Herrick’s real estate partners have enjoyed a strong working relationship for many years. Cohen, a 35-year veteran of commercial real estate, is the former executive vice president of Malkin Securities Corp., where for 15 years he directed the securities offerings of the real estate syndications of Malkin Holdings LLC, for which Herrick provided various legal services. Most of those syndicated properties, including the Empire State Building, now comprise the assets of Empire State Realty Trust, a publicly traded REIT.</p>
<p>Herrick partners Belinda Schwartz, Jonathan Adelsberg and Richard Morris advised on the formation of NHCohen Partners LLC.</p>
<p>“Herrick’s unique position as a facilitator in the real estate industry places us at the center of the action for owners, operators and developers looking for deals, equity, debt financing and strategic partners,” said Adelsberg. “This alliance will advance our ability to make valuable connections, and is very much a part of our culture of providing value above and beyond our lawyering. In addition, many of our high-net-worth clients may benefit from access to Ned’s vast experience with commercial real estate, and his prudent approach to investment.”</p>
<p>Cohen added: “Herrick’s partners and I share a deep understanding of commercial real estate and its multiple advantages as an alternative investment that can add diversity to a portfolio. I am extremely excited about this new relationship, which will enable me to expand the range of opportunities I can offer investors.”</p>
<p>In addition to NHCohen Partners, Ned Cohen founded an affiliated firm, NHCohen Capital LLC, a broker-dealer registered with the Securities and Exchange Commission, and a member of Financial Industry Regulatory Authority. NHCohen Capital will be the placement agent for the securities associated with the investment offerings of NHCohen Partners.</p>
<p>Founded in 1928, Herrick is a prominent 140-lawyer firm providing a full range of legal services.</p>
<p><strong>Original Link (globest.com)</strong>: <a href="http://www.globest.com/sites/globest/2015/03/12/nhcohen-and-herrick-feinstein-team-up/" target="_blank">NHCohen And Herrick, Feinstein Team Up</a></p>
