<p>Download: <a href="/pdf/hotelmanagement-net-transactions-nhcohen-partners-to-buy-texas-comfort-suites.pdf">hotelmanagement-net-transactions-nhcohen-partners-to-buy-texas-comfort-suites.pdf</a></p>
<p>New York City-based NHCohen Partners completed an equity raise of $6.1 million to facilitate the acquisition of the Comfort Suites Arlington hotel, situated midway between Dallas and Fort Worth along Interstate 30 and five miles from the DFW International Airport.</p>
<p>Affiliates of LBP Hotels and Waramaug LS Hotels, which had a minority interest in the four-story, 108-key, all-suites hotel, acquired 100 percent ownership through LBP Arlington Hospitality.</p>
<p>Arlington, the seventh largest city in Texas, occupies a central position in the Dallas-Fort Worth metroplex, midway between the two cities. Within a four-mile radius of Comfort Suites Arlington are the Dallas Cowboys’ AT&T Stadium, the Texas Rangers’ Globe Life Park, the Arlington Convention Center and the University of Texas Arlington campus. Two Six Flags amusement parks are within a 10-minute drive.</p>
<p>“Dallas-Fort Worth is an especially dynamic market, and hotels, in particular, are attracting strong attention from investors, in part on the anticipation that inflation eventually will become a positive factor for the hospitality industry,” Ned H. Cohen, president of NHCohen Partners, said in a statement. “In an inflationary environment, hospitality assets have the advantage and flexibility of setting room rates on a daily basis.”</p>
<p>Comfort Suites Arlington opened in 2009 and is managed by Interstate Hotels & Resorts, the world’s largest independent hospitality management company. Comfort Suites is a brand of Choice Hotels International, which has more than 6,400 hotels franchised around the world.</p>
<p>Asset management will be provided by Waramaug Hospitality. Cohen said members of the limited liability company that owns the Comfort Suites Arlington hotel will receive an annualized preferred return of 8 percent and can expect to enjoy partially tax-sheltered dividends and capital appreciation.</p>
<p>LBP and Waramaug LS Hotels currently own interests in 37 hospitality assets, with an aggregate of more than 4,100 rooms. Last year, NHCohen Partners raised capital that helped LBP purchase the Comfort Suites Raleigh-Durham Airport hotel adjoining Research Triangle Park in North Carolina. “This is an investment group with broad and deep experience in hospitality, and a sharp focus on markets with growth potential,” Cohen said in a statement.</p>
<p>Original Link: <a href="https://www.hotelmanagement.net/transactions/nhcohen-partners-to-buy-texas-comfort-suites">NHCohen Partners funds Texas Comfort Suites purchase</a></p>
