<p><strong>Download</strong>: <a href="/pdf/hotelbusiness-nhcohen-partners-completes-equity-raise-for-acquisition-of-comfort-suites-in-nc.pdf">hotelbusiness-nhcohen-partners-completes-equity-raise-for-acquisition-of-comfort-suites-in-nc.pdf</a></p>
<img src="../../img/comfort-suites-nc.jpg" alt="comfort suites image" class="leadership-headshot" />
<p>NEW YORK—NHCohen Partners has completed the equity raise for the acquisition of the Comfort Suites Raleigh Durham Airport/RTP hotel, located two miles from Research Triangle Park and five miles from Raleigh-Durham International Airport in Raleigh-Durham, NC.</p>
<p>The property is a five-story, 125-key all-suites, select-service hotel managed by Interstate Hotels and Resorts, a U.S.-based global hotel management company. The $8.5-million acquisition was sponsored by LBP Hotels, LLC, a venture headed by Paul Stern, a veteran in the hospitality investment space. The seller was a private investment group.</p>
<p>The hotel lies along Interstate 40, the primary commercial route through the Research Triangle area. Also nearby are Duke University, the University of North Carolina at Chapel Hill and other educational institutions and corporate demand generators.</p>
<p>Asset management will be provided by Waramaug Hospitality, a private hotel firm and co-investor in the ownership.</p>
<p>Ned H. Cohen, president of NHCohen Partners, noted that members of the limited liability company will receive an annualized preferred return of 8%. The sponsor arranged conservative long-term institutional financing on favorable terms, according to the company.</p>
<p>The sponsor and its affiliates, with more than 25-years’ experience in real estate investment, have interests in 40 hospitality properties, focusing on investing in income-producing hotels on behalf of family offices and high-net-worth individuals, according to the company. Cohen noted he sees a very attractive potential for well-located hospitality properties in growth regions, exemplified by this investment.</p>
<p>“NHCohen Partners facilitated the assembly of the equity portion for this investment, which should provide investors with steady and increasing dividends, partially tax-sheltered and capital appreciation,” said Paul Stern of LBP Hotels.</p>
<p><strong>Original Link (hotelbusiness.com)</strong>: <a href="http://www.hotelbusiness.com/RealEstate/NHCohen-Raises-Capital-to-Enable-LBP-Hotels-to-Acquire-Comfort-Suites-in-NC/54815">http://www.hotelbusiness.com/RealEstate/NHCohen-Raises-Capital-to-Enable-LBP-Hotels-to-Acquire-Comfort-Suites-in-NC/54815</a></p>
