<p><strong>NEW YORK CITY, December 09, 2014</strong> – Ned H. Cohen, founder and president of NHCohen Partners LLC, has been elected to serve on the Board of Advisors of 5 Stone Green Capital, a real estate investment fund focused on sustainability and the use of clean energy.</p>
<p>&#8220;Ned&#8217;s proven skills in building new businesses and understanding the concerns of investors as a fiduciary will make a valuable contribution to the growth of 5 Stone Green Capital,&#8221; says Doug Lawrence, founder and co-managing principal of the real estate fund. He adds:</p>
<p>&#8220;We look forward to his business acumen and capital markets expertise, as well as his thoughts about attracting investors and supporters who understand the attributes of investing in green real estate assets in particular, and real estate funds in general.&#8221;</p>
<p>Mr. Cohen will serve on a distinguished board that includes General Wesley Clark, former NATO Supreme Allied Commander in Europe; Stuart Brodsky, principal creator of the Environmental Protection Agency&#8217;s Energy Star program; and two past chairmen of branches of the Federal Reserve Bank: David Chen (Portland branch of the San Francisco Fed), who is now a principal of Equilibrium Capital Group; and Thomas Mackell, Jr. (Federal Reserve Bank of Richmond).</p>
<p>Mr. Cohen&#8217;s career in real estate investment spans more than 35 years. NHCohen Partners seeks opportunities for investors to participate in limited partnerships that provide equity to well-established real estate entrepreneurs for investments in quality real estate.  An affiliated entity, NHCohen Capital LLC, serves as placement agent for the securities issued by investment sponsors.  </p>
<p>Of his appointment to the 5 Stone Green Capital board, Mr. Cohen says:  &#8220;There is a growing recognition within the real estate community that buildings can have a significant effect on the environment. It&#8217;s a privilege to serve on the board of a company at the forefront of efforts to ensure that these effects are positive.&#8221;</p>
<p>Prior to forming his new firms, Mr. Cohen served for 15 years as executive vice president of Malkin Securities Corp., in which capacity he directed the securities offerings of the real estate syndications of Malkin Holdings LLC.  Most of the Malkin portfolio – including the Empire State Building, which was syndicated in 1961 – is now part of the publicly traded Empire State Realty Trust. </p>
<p>Mr. Cohen is a registered principal and operations professional with the Financial Industry Regulatory Authority (FINRA), and holds Series 22, 39, 63 and 99 securities licenses.</p>
<p>His prior senior positions comprise a broad range of in-depth experience in the complex, cyclical world of real estate and finance. He is a former partner of Bergman Real Estate Group in New Jersey, where he headed the firm&#8217;s acquisition and finance activities as well as its client advisory services. As a vice president of Unicorp American Corporation, he led the analysis and acquisition of Lincoln Savings Bank&#8217;s $1.8 billion real estate portfolio. </p>
<p>He also served as vice president of the premier nationwide real estate banking firm Eastdil Realty (now Eastdil Secured), where his clients included Chrysler Corp., Penn Mutual Life Insurance Co., New York State&#8217;s Urban Development Corp., and the Lake Placid Resort Hotel bankruptcy (which was the 1980 Winter Olympics headquarters). As a vice president of prominent real estate syndicator Integrated Resources, Mr. Cohen oversaw the acquisition and underwriting of office buildings and shopping centers for limited partnership and public fund investors.</p>
<p>Mr. Cohen&#8217;s career began in construction lending with what is today JPMorgan Chase Bank, following his graduation from Syracuse University.</p>
<hr>
<h2>Contact</h2>
<p>Rachel Antman, 646-699-7825; <a href="mailto:rantman@LVMgroup.com">rantman@LVMgroup.com</a><br>
Bob Rumerman, 917-288-3767; <a href="mailto:brumerman.editorial@gmail.com">brumerman.editorial@gmail.com</a></p>
