<p><strong>Download</strong>: <a href="/pdf/qa-with-ned-h-cohen-commercial-observer.pdf">qa-with-ned-h-cohen-commercial-observer.pdf</a></p>
<p><em><strong>Commercial Observer Finance</strong>: How did you get your start?</em><br />
<p><strong>Ned Cohen</strong>: At Syracuse University I studied urban sociology and economics and became interested in how our cities and society evolved from the 1940s postwar period, and the economics relating to that evolution. My  rst job after graduation was with J.P. Morgan Chase, as it is known today, where I learned about construction lending during a very expansive economic period. I worked with a few legendary and visionary developers and entrepreneurs (the names Bill Zeckendorf, James Rouse and Gerald Hines come to mind) who enabled me to broaden my perspective of real estate investment and  nance, as I set a goal of becoming an astute real estate professional.</p>
<p>In subsequent years, I worked for a midsize New Jersey-based developer, then expanded my horizon with the prominent real estate investment-banking firm Eastdil Secured. Later, with Integrated Resources, I became involved with the underwriting and acquisition of o ce buildings and shopping centers for limited partnership and public fund investors. At Unicorp American Corporation, I led the analysis and acquisition of Lincoln Savings Bank’s $1.8 billion real estate portfolio when that bank failed in the severe real estate recession of the late 1980s. In the 1990s, I became a partner of Bergman Real Estate Group in New Jersey, heading acquisition,  nance and client advisory services. So my  nance and equity background was very diverse, even before I joined Malkin Holdings to head Malkin Securities Corp.</p>
<p><em>Can you tell us about your recently announced alliance with law firm Herrick, Feinstein?</em><br />
Primarily, this alliance is in recognition of two facts: that income-producing real estate can be an important alternative investment, with many advantages, for individuals and family offices, and that limited partnerships are a vital source of funding for real estate entrepreneurs.</p>
<p>My objective is to identify and structure well conceived opportunities for investors to diversify their portfolios with direct ownership of real estate, while providing equity to experienced deal sponsors whose capital requirements are not fully satis ed by traditional lenders.</p>
<p>When appropriate, Herrick, Feinstein—whose real estate practice ranks among New York’s best and largest—will be a source of potential deal sponsors and equity investors, and my firm will provide quality investment services for Herrick clients. The partners and I share a very careful approach to investment, and already know we work well together. Malkin Holdings was a Herrick, Feinstein client during my 15 years at Malkin Securities. We both subscribe to the principles of disciplined underwriting and thorough due diligence imparted by the Malkin family when it introduced real estate syndication some 80 years ago.</p>
<p><em>You plan to focus on carefully structured, conservatively leveraged deals. Who will you target as a borrower?</em><br />
I’m looking for deal sponsors with deep experience and successful track records, whose projects need supplementary funding in the approximate range of $5 to $25 million. The deal must be founded on sound real estate fundamentals and realistic economics, and provide a viable exit strategy. Most types of income-producing property will be considered.</p>
<p><em>What’s the most interesting deal you have in the hopper?</em><br />
On an individual property basis, there’s an apartment project in a suburb of Atlanta that requires equity for acquisition and presents a rather unusual opportunity. SEC regulations preclude me from being more speci c without o ering statement, but this is an investment I regard enthusiastically. In addition, I’ll be raising equity for a fund sponsored by one of New York’s best-known real estate entities, which has been in business for about a half-century. It’s a solid firm with a conservative approach similar to mine.</p>
