<p><strong>Download</strong>: <a href="/pdf/rew-online-2015-09-03-stock-market-volatility-shines-spotlight-in-real-estate-attributes.pdf">rew-online-2015-09-03-stock-market-volatility-shines-spotlight-in-real-estate-attributes.pdf</a></p>
<p>Is the long-predicted bear market finally here, or are recent sharp declines merely a chance to load up on good stocks?</p>
<p>Since no one can truly know, prudence demands that greater attention be given to portfolio diversification, says Ned H. Cohen, president of NHCohen Partners LLC, whose firm focuses mainly on real estate limited partnerships.</p>
<p>&#8220;Direct ownership of quality real estate, modestly leveraged and acquired with clear, well planned exit strategies, has a long history of delivering steady income, capital gains, tax shelter benefits, protection against inflation and important estate-planning advantages,&#8221; Cohen points out.</p>
<p>&#8220;It&#8217;s time to give greater recognition to the fact that investment portfolios need not prosper or decline solely on the state of the stock and bond markets.&#8221;</p>
<p>Cohen is a 35-year veteran of real estate finance and investment. He served for 15 years as executive vice president of Malkin Securities Corp., the broker-dealer for the 10-million-square-foot Malkin Holdings commercial property portfolio (most of which now comprises Empire State Realty Trust, a REIT traded on the New York Stock Exchange).</p>
<p>&#8220;Today, there are investment opportunities offering dependable returns that well exceed typical stock and investment-grade bond yields,&#8221; he says.</p>
<p>&#8220;And with that current return comes an inflation hedge, a good prospect of higher value, some modest tax shelter, and a potential estate-planning tool that may provide a step-up in asset value to heirs.</p>
<p>&#8220;Investors should be cautioned, however, there is no liquidity of principal, so money should not be invested that might be needed during the term of the investment,&#8221; Cohen adds.</p>
<p>&#8220;My personal opinion is that the lack of liquidity also is a good thing. It removes the kind of volatility that results in the stock market when investors overreact to perceived positive or negative trends and events.&#8221;</p>
<p>He notes that publicly traded real estate investment trusts share many of the characteristics of other stock market investments and therefore do not offer the same degree of stability of limited partnership units representing direct ownership of property.</p>
<p>&#8220;The performance of direct real estate investments is not correlated to the stock market and will generally provide a more stable flow of distributions,&#8221; says Cohen.</p>
<p>&#8220;With direct ownership, you are investing in a tangible asset rather than in a piece of paper. Those assets can weather changing economic cycles, creating long-term value.</p>
<p>But they must be chosen by experienced, successful real estate entrepreneurs, and the investment partnerships must be structured by finance experts to protect investors against bumps in the road and provide well thought out plans for asset disposition.&#8221;</p>
<p>COPYRIGHT 2015 REAL ESTATE WEEKLY. ALL RIGHTS RESERVED.</p>
<p><strong>Original Link (rew-online.com)</strong>: <a href="http://rew-online.com/2015/09/03/stock-market-volatility-shines-spotlight-in-real-estate-attributes/" target="_blank">http://rew-online.com/2015/09/03/stock-market-volatility-shines-spotlight-in-real-estate-attributes/</a></p>
