<p><strong>Download</strong>: <a href="/pdf/stock-markets-ominous-volatility-shines-spotlight-on-real-estates-defensive-attributes-says-ned-h-cohen.pdf">globest-sites-globest-2015-03-12-nhcohen-and-herrick-feinstein-team-up.pdf</a></p>
<p>Direct Ownership of Real Property Adds Diversification To Investment Portfolios and Mitigates Other Risks</p>
<p>Is the long-predicted bear market finally here, or are recent sharp declines merely a chance to load up on good stocks? Since no one can truly know, prudence demands that greater attention be given to portfolio diversification, says Ned H. Cohen, president of NHCohen Partners LLC, whose firm focuses mainly on real estate limited partnerships.</p>
<p>“Direct ownership of quality real estate, modestly leveraged and acquired with clear, well planned exit strategies, has a long history of delivering steady income, capital gains, tax shelter benefits, protection against inflation and important estate-planning advantages,” Mr. Cohen points out. “It’s time to give greater recognition to the fact that investment portfolios need not prosper or decline solely on the state of the stock and bond markets.”</p>
<p>Mr. Cohen is a 35-year veteran of real estate finance and investment. He served for 15 years as executive vice president of Malkin Securities Corp., the broker-dealer for the 10-million-square-foot Malkin Holdings commercial property portfolio (most of which now comprises Empire State Realty Trust, a REIT traded on the New York Stock Exchange).</p>
<p>“Today, there are investment opportunities offering dependable returns that well exceed typical stock and investment-grade bond yields,” he says. “And with that current return comes an inflation hedge, a good prospect of higher value, some modest tax shelter, and a potential estate-planning tool that may provide a step-up in asset value to heirs.</p>
<p>“Investors should be cautioned, however, there is no liquidity of principal, so money should not be invested that might be needed during the term of the investment,” Mr. Cohen adds. “My personal opinion is that the lack of liquidity also is a good thing. It removes the kind of volatility that results in the stock market when investors overreact to perceived positive or negative trends and events.”</p>
<p>He notes that publicly traded real estate investment trusts share many of the characteristics of other stock market investments and therefore do not offer the same degree of stability of limited partnership units representing direct ownership of property. “The performance of direct real estate investments is not correlated to the stock market and will generally provide a more stable flow of distributions,” says Mr. Cohen.</p>
<p>“With direct ownership, you are investing in a tangible asset rather than in a piece of paper. Those assets can weather changing economic cycles, creating long-term value. But they must be chosen by experienced, successful real estate entrepreneurs, and the investment partnerships must be structured by finance experts to protect investors against bumps in the road and provide well thought out plans for asset disposition.”</p>
<p><strong>About NHCohen Partners, LLC</strong></p>
<p>NHCohen Partners is an investment firm that identifies quality opportunities for high-net-worth individuals and family entities to diversify their holdings, with a special emphasis on real estate. The firm carefully evaluates partnership structures to help investors realize all of the potential benefits of real estate, including income, capital appreciation, and tax and estate planning advantages, with preservation of capital receiving the highest priority. For more information, please visit www.nhcohenpartners.com.</p>
<p><strong>Original Link (globest.com)</strong>: <a href="http://newyork.citybizlist.com/article/295743/stock-markets-ominous-volatility-shines-spotlight-on-real-estates-defensive-attributes-says-ned-h-cohen" target="_blank">Stock Market’s Ominous Volatility Shines Spotlight On Real Estate’s Defensive Attributes, Says Ned H. Cohen</a></p>
