<img src="<?php echo base_url('img/ned_cohen-headshot.jpg'); ?>" class="leadership-headshot">
<p>Ned H. Cohen is founder and president of Manhattan-based NHCohen Partners LLC and its affiliated registered broker-dealer, NHCohen Capital LLC. NHCohen Partners identifies quality alternative investment opportunities for high-net-worth individuals and family offices – primarily in real estate – applying the perspective and insight acquired by Mr. Cohen over a career that spans more than three and a half decades.</p>
<p>Mr. Cohen was executive vice president of Malkin Securities Corp., a former FINRA-registered broker-dealer affiliated with Malkin Holdings LLC, where for 15 years he directed the private placement of equity in syndications structured by the firm, sourced capital from accredited and institutional investors for new investments, and introduced a broad range of enhancements in investor services. He also was a member of the Investment Committee and served as chief compliance officer.</p>
<p>(The Malkin family has been preeminent in real estate syndication, having created the first real estate partnerships in the 1930s.  Its syndications included the Empire State Building and many other widely known properties.)
During his tenure at Malkin Securities, Mr. Cohen concluded syndications that raised more than $400 million of equity for existing and newly formed entities owning various types of income-producing property.  He also oversaw an innovative series of high-yield preferred-equity and subordinate debt funds that provided mezzanine funding as an important capital source for real estate entrepreneurs.</p>
<p>Mr. Cohen's prior senior positions comprise a broad range of in-depth experience in the complex, cyclical world of real estate and finance. He is a former partner of Bergman Real Estate Group in New Jersey, where he headed the firm's acquisition and finance activities as well as its client advisory services. As a vice president of Unicorp American Corporation, he led the analysis and acquisition of Lincoln Savings Bank's $1.8 billion real estate portfolio.</p>
<p>He also served as vice president of the premier nationwide real estate banking firm Eastdil Realty (now Eastdil Secured), where his clients included Chrysler Corp., Penn Mutual Life Insurance Co., New York State's Urban Development Corp., and the Lake Placid Resort Hotel bankruptcy (which was the 1980 Winter Olympics headquarters). As a vice president of prominent real estate syndicator Integrated Resources, Mr. Cohen oversaw the acquisition and underwriting of office buildings and shopping centers for limited partnership and public fund investors.</p>
<p>Mr. Cohen's career began in construction lending with what is today JPMorgan Chase Bank, following his graduation from Syracuse University.</p>
<p>Mr. Cohen was recently elected to serve on the Board of Advisors of 5 Stone Green Capital LLC, a real estate investment fund focused on sustainability and the use of clean energy.  He is a registered principal and operations professional with FINRA (the Financial Industry Regulatory Authority), and holds Series 22, 39, 63 and 99 securities licenses.</p>
<h3>Publications:</h3>
<p>"<a href="http://napfa.org/library_room/article.asp?CATEGORY_ID=3&LR_ID=9819&print=y" rel="external">Real Estate Remains Good Alternative Investment, but Surfeit of Institutional Capital Requires Investor Discretion</a>," NAPFA Advisor Magazine, January 2007</p>
<p>"<a href="http://napfa.org/library_room/article.asp?CATEGORY_ID=3&LR_ID=9887&print=y" rel="external">Credit Tightening in Commercial Real Estate May Presage Return of Value-Oriented Investment Opportunities</a>," September 2007, NAPFA Advisor Magazine.</p>
