<p>Balance and diversification are the hallmarks of a strong investment portfolio.  Specifically allocating real estate to a portion of a stock and bond portfolio can help provide diversification and smooth risk.  Portfolio diversification with real estate offerings can provide the benefits of regular cash distributions, conservative leverage, protection against inflation and greater stability to overall portfolio performance.</p>
<ul>
	<li><strong>Portfolio Diversification</strong> – Additional layers of diversification can come from the real estate portfolio itself, if it is diversified by property type, location, tenant, industry and/or lease term.  Investment in real estate may provide diversification into an asset outside the stock market (equities market) that has a low historical price correlation to traditional investments.</li>
	<li><strong>Income</strong> – The leasing of high quality real estate is generally designed with the objective of providing investors with a recurring stream of income.</li>
	<li><strong>Potential Hedge Against Inflation</strong> – Rental increases are generally built into long-term leases in the retail, office and industrial sectors.</li>
</ul>
<p>Investors should consider their allocation in real estate a long-term investment, in which they do not require immediate liquidity.</p>
<p>An investment in an offering presented by NHCohen Capital LLC is suitable only for individuals and entities considered to be relatively sophisticated and financially independent under the securities laws − “Accredited Investors”− who have no need for liquidity with respect to such investments. </p>
<p>All investments, including those in real estate, involve risk, which may include property market and interest rate fluctuations and illiquidity.  Therefore, a comprehensive evaluation and detailed review of all investment documents, including the private placement memorandum, the sole means for offering any investment presented by NHCohen Capital to qualified and Accredited Investors registered with NHCohen Capital, should be undertaken before deciding whether to make such investment. </p>
<p>Each investor should review his or her tax situation to determine if a contemplated investment is appropriate.  Finally, because tax laws are subject to change, your accountant or tax adviser should be consulted before proceeding with any investment.</p>
