<h2>IMPORTANT LEGAL INFORMATION</h2>
<p>Please read these Terms of Use carefully before using our website www.nhcohenpartners.com. If you do not agree to these Terms of Use, please do not use our website. By using our website, including all material provided on our website, you agree to be bound by these Terms of Use.</p>
<h2>No Solicitation or Offer is Intended by Use of this Site</h2>
<p>The information provided on this site is not intended for distribution to, or use by, any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject NHCohen Partners LLC or its affiliates to any registration requirement within such jurisdiction or country. Neither the information nor any opinion contained in this site constitutes a solicitation or offer by NHCohen Partners LLC or its affiliates to buy or sell any securities, real estate or other investments or assets or provide any investment advice or service.</p>
<h2>Disclaimer of Warranty and Limitation of Liability</h2>
<p>The information on this site is provided "AS IS." NHCOHEN PARTNERS LLC DOES NOT WARRANT THE ACCURACY OF THE INFORMATION AND MATERIALS PROVIDED HEREIN, EITHER EXPRESSLY OR IMPLIEDLY, AND EXPRESSLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE AND WARRANTIES OF NON-INFRINGEMENT OF PROPRIETARY RIGHTS, ALL TO THE FULLEST EXTENT ALLOWED BY LAW. NHCohen Partners LLC will not be responsible for any loss or damage that could result from interception by third parties of any information made available to you via this site. Although the information provided to you on this site is obtained or compiled from sources we believe to be reliable, NHCohen Partners LLC cannot and does not guarantee the accuracy, validity, timeliness or completeness of any information or data made available to you for any particular purpose. Neither NHCohen Partners LLC, nor any of its affiliates, directors, shareholders, officers or employees, nor any third party vendor will have liability or responsibility of any kind to you for any loss or damage that you may incur from any failure or interruption of this site, from any act or omission of any other party involved in providing this site or the data contained herein, or from any other cause relating to your use or access, or the failure of your use or access, in connection with this site or these materials, whether or not the related circumstances may have been within the control of NHCohen Partners LLC or of any vendor providing software or services support. In no event will NHCohen Partners LLC, its affiliates or any such parties be liable to you for any direct, special, indirect, consequential, incidental damages or any other damages of any kind, even if NHCohen Partners LLC or any other party have been advised of the possibility thereof.</p>
<h2>Copyrights, Trademarks and Other Intellectual Property</h2>
<p>All material contained on our website, and the compilation of it, are our property and are protected by United States and international copyright laws. All trademarks, service marks and trade names, including but not limited to NHCohen Partners LLC, NHCohen Capital LLC and associated block logos, are trademarks of NHCohen Partners LLC and/or its affiliates and are proprietary to us. No material from our website may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except that you may download and print material available on this site (a) as may be expressly permitted by our site and/or (b) solely for your personal, noncommercial use, provided that (i) you keep intact all copyright notices, trademark legends, author attributions, and other proprietary notices, (ii) you make no modification to the materials, and (iii) you do not download quantities of materials to a database that can be used to avoid future downloads from our website. Except as may be permitted by law, you must obtain our written permission before using any copyrighted material from our websites. You do not acquire any ownership rights by downloading material from our website.</p>
<h2>Use of Links</h2>
<p>Should the viewer leave this site via a link contained herein and view content that is not provided by NHCohen Partners LLC, the viewer does so at its own risk. The content to which you link will not have been developed or otherwise reviewed by NHCohen Partners LLC, which is not responsible for damages or losses caused by any delays, defects or omissions that may exist in the services, information or other content provided in such site, whether actual, alleged, consequential or punitive. NHCohen Partners LLC makes no guarantee or representation as to, and shall have no liability for, any electronic content delivered by any third party, including, without limitation, the accuracy, subject matter, quality or timeliness of any electronic content.</p>
<h2>Modifications</h2>
<p>We may modify these Terms of Use at any time and at our sole discretion by posting the modified Terms of Use on our website. The modifications will be effective upon posting (unless some other date is specified). You should review these Terms of Use periodically so that you are aware of any modifications. Your use of our website constitutes your acceptance of the Terms of Use in their then-current form.</p>
<h2>Dispute Resolution</h2>
<p>Any disputes , actions or proceedings relating to these Terms of Use, or to your access to or use of the site, will be governed by the laws of the State of New York, without regard to its conflict of law rules, and must be brought in the federal or state courts in the City and County of New York. By using our website, you irrevocably consent to the exclusive jurisdiction and venue of those courts.</p><p>If you are an investor in any investment in which we acted as placement agent, nothing in these Terms of Use will supersede any provision of any agreement with respect to any such investment.</p>
<h2>Privacy Policy</h2>
<p>Please review our Privacy Policy, which governs the use of personal and identifying information.</p>
<h2>Use in other Jurisdictions</h2>
<p>NHCohen Partners LLC does not operate in all U.S. and foreign jurisdictions. Some products and services may not be available in all jurisdictions or to all clients.</p>
